services:
  - type: web
    name: web-poly-exam
    env: python
    pythonVersion: '3.11.7'
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: '3.11.7'